README.md
=> Add initial project info

ro_help/hub/templates/developed-by.html
Closes https://github.com/code4romania/ro-help/issues/120
Open on local. Click the icon, seen that the URL is set correctly.
=> Update aadr link in developed by tab #120

ro_help/ro_help/settings/base.py
=> Add media file config to settings

ro_help/hub/templates/header.html
=> Add login and register buttons in nav bar

ro_help/hub/templates/about.html
https://github.com/code4romania/ro-help/pull/146
=> added content to about.html to close PR 146

ro_help/hub/forms.py
=> included _ in forms

ro_help/hub/templates/footer.html
Closes https://github.com/code4romania/ro-help/issues/167
=> Fixed footer link for cetrebuiesafac.ro

ro_help/hub/templates/ngo/list.html
Closes https://github.com/code4romania/ro-help/issues/149
When there are no results matching the filtering query, we no longer display pagination.
Make some weird filters locally which should result in an empty queryset. Pagination is no longer displayed
=> handle empty results page.

ro_help/hub/templates/ngo/base.html, ro_help/static/data/sidebar_en.json, ro_help/static/data/sidebar_hu.json, ro_help/static/data/sidebar_ro.json
Closes https://github.com/code4romania/ro-help/issues/132
This PR updates `json` files used to read sidebar links to related projects and makes sure they link to the rig places. 
Missing translations for en/hu languages though.
Navigate to index, be amazed by sidebar links :)
=> updated sidebar links.

ro_help/hub/management/commands/seed.py
=> Do not seed money needs

ro_help/ro_help/settings/base.py
=> Take the static files out of S3

ro_help/mobilpay/apps.py, ro_help/ro_help/settings/base.py
=> Changed icon for mobilpay

.gitignore, ro_help/hub/admin.py
=> Added better search and filters in admin

ro_help/hub/management/commands/seed.py, ro_help/mobilpay/mobilpay/util/encrypt_data.py, ro_help/mobilpay/views.py
=> read mobilpay keys from s3

ro_help/hub/management/commands/seed.py, ro_help/mobilpay/mobilpay/util/encrypt_data.py, ro_help/mobilpay/utils.py, ro_help/mobilpay/views.py
=> Fix mobilpay s3

ro_help/hub/views.py
Closes https://github.com/code4romania/ro-help/issues/179
Not much else to say
=> use .distinct() when preparing search results queryset.

ro_help/static/css/hub.css
[Issue-194](https://github.com/code4romania/ro-help/issues/194)
The fix is made in similar way:
Pagination styling is not touched. 
Let me know if there any tests we should run for this css change.
=> Added space for pagination on Donation card

ro_help/hub/templates/ngo/base.html, ro_help/static/css/hub.css
=> sidebar font sizes

ro_help/ro_help/settings/base.py
=> correct path to storage_backends

ro_help/hub/templates/ngo/base.html, ro_help/static/css/hub.css
Closes #133 
Submits the search form when clicking the search icon
Make cursor pointer when over search icon
Only HTML changes
Search by different terms using the icon instead of enter
=> [search-button] submit search for by using search icon

ro_help/hub/views.py
https://github.com/code4romania/ro-help/issues/214
Local appliance.
=> Added the KindFilter class to the List class.

ro_help/hub/templates/ngo/list.html
=> Fix pagination buttons on the needs listing page

ro_help/hub/admin.py
=> Added filters and search options on Register requests votes admin page

ro_help/hub/templates/ngo/list.html, ro_help/hub/templates/register-ngo.html, ro_help/static/css/hub.css
Styling of NGO need boxes according to new Figma design
=> new ngo need box styling

docker-compose.yml
this PR updates `docker-compose.yml` and adds `tty: true`
mainly because someone might wanna use `pdb` for debugging :-D
=> tty: true in docker-compose yml file.

ro_help/hub/admin.py, ro_help/hub/templates/ngo/list.html, ro_help/hub/views.py
Closes #213 
- Search vector no longer takes tag name into consideration
- `NGONeedListView.get_queryset()` handles `tag` filters as _special case_
- There's a new dropdown with tags in `list.html` which allows multiple tags to be selected.
=> added tag dropdown filter. removed tag name from search vector.

.github/CODEOWNERS
=> Add andreiio as codeowner

ro_help/ro_help/settings/dev.py
=> Deactivate debug email in dev

buildspec.yml, ro_help/hub/migrations/0040_auto_20200331_0856.py, ro_help/hub/views.py, ro_help/ro_help/settings/base.py, ro_help/ro_help/urls.py
=> Add ENVIRONMENT build arg to buildspec

docker/web/docker-entrypoint
=> Increase gunicorn workers and put info back

ro_help/hub/admin.py
=> fix accept transactions

ro_help/mobilpay/admin.py
=> added filters and search to payment response

ro_help/hub/forms.py, ro_help/hub/templates/ngo/register_request.html
=> Remove CIF as mandatory, remove text from NGO signup form

requirements-prod.txt, ro_help/hub/admin.py, ro_help/hub/templatetags/meta_tags.py, ro_help/mobilpay/admin.py, ro_help/ro_help/settings/base.py
=> Add Sentry. Paint it black

requirements-prod.txt, ro_help/hub/admin.py, ro_help/hub/templatetags/meta_tags.py, ro_help/mobilpay/admin.py, ro_help/ro_help/settings/base.py
=> Add Sentry. Paint it black (#287)

ro_help/hub/models.py, ro_help/locale/ro/LC_MESSAGES/django.po
=> Add translations

requirements-prod.txt, ro_help/hub/admin.py, ro_help/hub/models.py, ro_help/hub/templatetags/meta_tags.py, ro_help/locale/ro/LC_MESSAGES/django.po, ro_help/mobilpay/admin.py, ro_help/ro_help/settings/base.py
=> Add sentry and translations

ro_help/hub/templates/ngo/detail.html, ro_help/hub/templates/shared/pagination.html, ro_help/static/css/hub.css
Closes 
moved pagination to bottom for ngo needs accordion, fixed centering of pagination elements 
=> pagination fixes

ro_help/ro_help/settings/base.py
=> Add thumbnail storage

requirements.txt, ro_help/hub/templates/admin/change_form.html
=> Added sentry to req and fixed checkbox in inline forms

ro_help/hub/admin.py
Fixed the creation of multiple money needs when you save the NGO model in admin.
=> fix duplicated money needs

ro_help/hub/admin.py
=> Fix duplicated money needs 

ro_help/hub/templates/ngo/list.html
=> Hide tags from Money needs page

requirements.txt, ro_help/hub/templates/ngo/list.html, ro_help/ro_help/settings/base.py, ro_help/static/css/hub.css
Logos in list were different sizes
Logo on ngo page was skewed in safari
=> fixed logo img issues

requirements.txt, ro_help/hub/templates/ngo/list.html, ro_help/ro_help/settings/base.py, ro_help/static/css/hub.css
=> Hide tags on Money page. Fix logos.

ro_help/hub/templates/rules.html
=> sign not sing :(

ro_help/hub/templates/admin/base_site.html, ro_help/static/css/admin/style.css
- Styling of the language selector on the admin page
=> language selector styling in admin

ro_help/hub/templates/admin/base_site.html, ro_help/hub/templates/rules.html, ro_help/static/css/admin/style.css
=> Style language selector

ro_help/hub/admin.py
Solves https://sentry.io/organizations/code-for-romania/issues/1607349974/?query=is%3Aunresolved
=> Don't reuse _ variable

ro_help/hub/templates/about.html, ro_help/hub/templates/contact.html, ro_help/hub/templates/cookies.html, ro_help/hub/templates/rules.html, ro_help/hub/templates/terms_and_conditions.html
=> fixed layout for static pages

ro_help/hub/templates/mail/new_payment.html, ro_help/mobilpay/templates/mobilpay/response.html
ă :smile: 
also some small layout improvements to new payment email template
=> added missing diacritics

ro_help/hub/templates/mail/new_payment.html, ro_help/mobilpay/templates/mobilpay/response.html
* added missing diacritics
* updated new payment email template
Closes 
=> added missing diacritics (#334)

ro_help/hub/admin.py
=> Hide money need in admin for non admins

ro_help/hub/templates/ngo/base.html, ro_help/static/css/hub.css
=> Move Red Cross

ro_help/hub/templates/ngo/base.html, ro_help/static/css/hub.css
=> red cross banner for mobile

ro_help/hub/management/commands/seed.py, ro_help/hub/templates/ngo/base.html, ro_help/static/css/hub.css
=> Move Red Cross banner

requirements.txt, ro_help/hub/templates/admin_totals/change_list_results_totals.html, ro_help/hub/templates/admin_totals/change_list_totals.html, ro_help/mobilpay/admin.py, ro_help/ro_help/settings/base.py
=> Sum donated

ro_help/hub/admin.py
=> delete old money need before create the new one

README.md
changes `https://dev.rohelp.ro` to `http://dev.rohelp.ro`
=> Update development URL inside README.md

ro_help/ro_help/settings/base.py, ro_help/ro_help/settings/dev.py, ro_help/ro_help/settings/prod.py
=> Allow Debug and Sentry to be configured from env

ro_help/hub/views.py
=>  Set noindex header for search results page
